// Package test 集成测试:用 httptest 起完整路由,不依赖外部服务。
package test

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/yinyin/myblog/internal/bootstrap"
	"github.com/yinyin/myblog/internal/config"
	"github.com/yinyin/myblog/internal/middleware"
	"github.com/yinyin/myblog/internal/pkg/errcode"
	"github.com/yinyin/myblog/internal/pkg/logger"
	"github.com/yinyin/myblog/internal/router"
)

func newTestEngine(t *testing.T) *gin.Engine {
	t.Helper()
	if err := logger.Init(logger.Config{Level: "error", Format: "json", Output: "stdout"}); err != nil {
		t.Fatalf("logger init: %v", err)
	}
	cfg := &config.Config{
		Server: config.ServerConfig{Mode: gin.TestMode},
	}
	return bootstrap.BuildEngine(cfg, "test", router.Deps{})
}

func TestHealth_OK_ReturnsUnifiedResponse(t *testing.T) {
	engine := newTestEngine(t)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/public/health", nil)
	rr := httptest.NewRecorder()
	engine.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("want 200, got %d, body=%s", rr.Code, rr.Body.String())
	}

	var body struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
		Data    struct {
			Status  string `json:"status"`
			Service string `json:"service"`
			Version string `json:"version"`
			Ts      int64  `json:"ts"`
		} `json:"data"`
	}
	if err := json.Unmarshal(rr.Body.Bytes(), &body); err != nil {
		t.Fatalf("unmarshal body: %v, raw=%s", err, rr.Body.String())
	}

	if body.Code != int(errcode.OK) {
		t.Errorf("want code=0, got %d", body.Code)
	}
	if body.Message != "ok" {
		t.Errorf("want message=ok, got %q", body.Message)
	}
	if body.Data.Status != "up" {
		t.Errorf("want data.status=up, got %q", body.Data.Status)
	}
	if body.Data.Service == "" {
		t.Errorf("data.service should not be empty")
	}
	if body.Data.Ts <= 0 {
		t.Errorf("data.ts should be positive, got %d", body.Data.Ts)
	}
}

func TestHealth_TraceIDHeader_EchoedBack(t *testing.T) {
	engine := newTestEngine(t)

	tid := "trace-under-test-0001"
	req := httptest.NewRequest(http.MethodGet, "/api/v1/public/health", nil)
	req.Header.Set(middleware.TraceIDHeader, tid)
	rr := httptest.NewRecorder()
	engine.ServeHTTP(rr, req)

	if got := rr.Header().Get(middleware.TraceIDHeader); got != tid {
		t.Errorf("trace id should be echoed, want %q, got %q", tid, got)
	}
}

func TestHealth_TraceIDHeader_AutoGenerated(t *testing.T) {
	engine := newTestEngine(t)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/public/health", nil)
	rr := httptest.NewRecorder()
	engine.ServeHTTP(rr, req)

	if got := rr.Header().Get(middleware.TraceIDHeader); got == "" {
		t.Errorf("trace id should be auto-generated when absent")
	}
}

func TestRecover_PanicReturnsUnified500(t *testing.T) {
	engine := newTestEngine(t)
	engine.GET("/boom", func(c *gin.Context) { panic("boom") })

	req := httptest.NewRequest(http.MethodGet, "/boom", nil)
	rr := httptest.NewRecorder()
	engine.ServeHTTP(rr, req)

	if rr.Code != http.StatusInternalServerError {
		t.Fatalf("want 500, got %d", rr.Code)
	}
	var body struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	if err := json.Unmarshal(rr.Body.Bytes(), &body); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if body.Code != int(errcode.ErrInternal) {
		t.Errorf("want code=%d, got %d", errcode.ErrInternal, body.Code)
	}
}
